name: Build

on:
  push:
    branches:
      - '**'
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn --frozen-lockfile
    - run: yarn run tsc
    - run: yarn run generate
